### PR TITLE
Overhaul python 2

### PR DESCRIPTION
**Pull request by gonuke**
In addition to moving some files back to better locations, this has many upgrades of the content.

### CODE REVIEW

**Comment by gonuke** [comment]
@dmnielsen needs to review some of these since she is teaching it...

**Comment by gonuke** [comment]
I need to fix the breadcrumbs and will do so now

**Comment by lmichael107** [comment]
FYI, GitHub indicates conflicts that need to be resolved before this pull request can be merged.

**Comment by gonuke** [comment]
I was expecting that when the other PR's got pulled.  I think I resolved it now with a rebase.

**Pull request merged**
