### PR TITLE
updates stats.py and Revert_and_branch.md to work nice with the testing ...

### PR DESCRIPTION
**Pull request by gidden**
...module

Hi everyone, especially @kbroman. This PR updates the `stats.py` file and the `Revert_and_branch.md` file to be able to coexist without rewriting much of the testing tutorial. Instead of implementing `var()` I suggested implementing `median()` with (hopefully) sufficient hints. At issue is that the testing module a) assumes `std()` is empty and a simplified `mean()` function.

### CODE REVIEW

**Comment by gidden** [comment]
note that we've covered even/odd using `% 2` in earlier lessons.

**Comment by gidden** [comment]
still, I recognize that this isn't nearly as easy as implementing `var()`, and while I don't want to take away from the point of the lesson (`git add`/`git commit`), I also don't want to completely rewrite the testing module.

**Comment by lmichael107** [comment]
I'll wait a bit for @kbroman to see this, but will otherwise merge this evening.

**Comment by gidden** [comment]
note that we also have a median function implementation in the collaborate section

**Comment by kbroman** [comment]
Need to change `numlist` to `vals` in [python/testing/stats.py lines 3-4](https://github.com/gidden/boot-camps/blob/stats/python/testing/stats.py#L3-L4)

**Comment by kbroman** [comment]
@lmichael107 Could you go ahead and merge all of the edits from @gidden so that we can all start the cleanup? I'm finding it a bit confusing to understand the current state of things.

**Comment by gidden** [comment]
Hi @kbroman -- for clarification -- the only changes I needed to make to your content was your `var()` addition example, specifically because it depends on `std()` being implemented, which is covered in the testing section.  

Because we `cp` the file from `python/testing/stats.py`, and because I did not want to completely rewrite the testing module, I had to update `python/testing/stats.py` to fit the testing module (i.e. a "simpler" `mean()` function and no `std()` function).

**Pull request merged**
