### PR TITLE
New survey data

### PR DESCRIPTION
**Pull request by alexhanna**
Generated a new script for the fake survey data, plus ran it once to generate new data. Removed the cochlear implant daa.

### CODE REVIEW

**Comment by gonuke** [comment]
Thanks @alexhanna .  It's hard to review this with so many changes, but it's probably the only way.

**Comment by gonuke** [comment]
Should we also update the lessons to this data as part of the same PR?

**Comment by alexhanna** [comment]
Yes, we discussed necessary changes in our meeting on Monday.

On Tue, May 19, 2015 at 6:31 PM, Paul Wilson notifications@github.com
wrote:

> Should we also update the lessons to this data as part of the same PR?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/UW-Madison-ACI/boot-camps/pull/185#issuecomment-103697356
> .

## 

Alex Hanna
http://alex-hanna.com
@alexhanna

**Comment by lmichael107** [comment]
Yes, I'll be making the corresponding changes to the "Shell" and "Automation" lesson language, as a result of the meeting all instructors had on Monday of last week.

**Pull request merged**
