### PR TITLE
Two small fixes to the automation session

### PR DESCRIPTION
**Pull request by kbroman**
- remove the bit with `~` within a shell variable.
- mention `.bash_profile` (rather than `.bashrc`) on Mac.

### CODE REVIEW

**Comment by gonuke** [comment]
What about this: http://www.joshstaiger.org/archives/2005/07/bash_profile_vs.html

On one hand it is more to throw in there, on the other, it gives a more generic solution....?

**Comment by kbroman** [comment]
That's actually what I do, but it doesn't seem like something we want to devote time to.

Maybe we could add an aside

> The truth is slightly more complicated; see [this discussion](http://www.joshstaiger.org/archives/2005/07/bash_profile_vs.html).

**Comment by gonuke** [comment]
That seems like a good compromise.  Do you want to throw it into this PR?

**Comment by kbroman** [comment]
Will do.

**Comment by kbroman** [comment]
Added in [this commit](https://github.com/kbroman/swc-boot-camps/commit/db537e3f19d8190124a5be8f235902c40e317700).

**Pull request merged**
