### PR TITLE
Changes to git revert/branch session

### PR DESCRIPTION
**Pull request by kbroman**
- Add refresher of git add/commit etc from the first day
- Exercise using `git branch` relied on testing discussion ([see Issue 88](https://github.com/UW-Madison-ACI/boot-camps/issues/88)); instead have students implement a variance function.
- **Note**: still need caution about location of the students' `stats.py` file (will they have cloned the boot-camps repository?

### CODE REVIEW

**Comment by lmichael107** [comment]
I'm just wondering if we can get a second set of eyes on this, from someone (like Matt?) who is actively working on the rest of our Git curriculum. Thanks -L

**Comment by gidden** [comment]
also looks good. @kbroman, do we need to update the navigation links at the top?

**Comment by lmichael107** [comment]
Yes. The main schedule also needs to be updated (and checked) for the right
links. -Lauren

**Comment by gidden** [comment]
Hey @kbroman, I'm going through the full set of git lessons to make sure we're consistent (i.e., `simplestats`, `stats.py`, etc.). I'm planning to update the links as well, just FYI. PR should be in soon^TM.

**Pull request merged**
