### PR TITLE
Fix breadcrumbs from Make Incremental Changes back to Don't Repeat Yours...

### PR DESCRIPTION
**Pull request by kliph**
...elf

### CODE REVIEW

**Comment by gidden** [comment]
@lmichael107, @gonuke, @kliph it appears I don't have write access..

**Comment by kliph** [comment]
Doesn't look like I do either...

**Comment by lmichael107** [comment]
I've added permissions back for those in the Boot-Camp-Admin group of collaborators. Should be able to merge now.

**Comment by kliph** [comment]
Thanks!

**Pull request merged**
