### PR TITLE
Add PATH modification for our servers...

### PR DESCRIPTION
**Pull request by njvack**
without this, people will run a python 2.6 ipython and stuff won't work.

### CODE REVIEW

**Comment by gidden** [comment]
They will have to do this every time they open a shell if so. Since this suggests copying and pasting something in the terminal, why not 

```
echo 'export PATH=/apps/python27/x86_64_sci6/bin:$PATH' >> .bashrc
```

**Comment by gidden** [comment]
with an `&& source ~/.bashrc` of course

**Comment by gidden** [comment]
Also, the rest of our bash docs start with a `$`, this should probably
as well

On Thu, Aug 7, 2014 at 10:25 AM, Nate Vack notifications@github.com wrote:

> ## without this, people will run a python 2.6 ipython and stuff won't work.
> 
> You can merge this Pull Request by running
> 
>   git pull https://github.com/njvack/boot-camps 2014-08-04-Davidson
> 
> Or view, comment on, or merge it at:
> 
>   https://github.com/UW-Madison-ACI/boot-camps/pull/62
> Commit Summary
> - Add PATH modification for our servers...
> 
> File Changes
> - _M_ python/writing_code_for_people/Readme.md
>   https://github.com/UW-Madison-ACI/boot-camps/pull/62/files#diff-0
>   (9)
> 
> Patch Links:
> - https://github.com/UW-Madison-ACI/boot-camps/pull/62.patch
> - https://github.com/UW-Madison-ACI/boot-camps/pull/62.diff
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/UW-Madison-ACI/boot-camps/pull/62.

## 

Matthew Gidden
Ph.D. Candidate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Comment by njvack** [comment]
Having everyone in our lab modify their .bashrc sounds like a recipe for post-class surprises. If we want editing startup files to be part of the curriculum, we should make it part of the curriculum.

**Comment by gidden** [comment]
Hmmm, normally we run bootcamps on one-time use accounts that get logged
into over more than one day. Different use case.

On Thu, Aug 7, 2014 at 10:33 AM, Nate Vack notifications@github.com wrote:

> Having everyone in our lab modify their .bashrc sounds like a recipe for
> post-class surprises. If we want editing startup files to be part of the
> curriculum, we should make it part of the curriculum.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/UW-Madison-ACI/boot-camps/pull/62#issuecomment-51488596
> .

## 

Matthew Gidden
Ph.D. Candidate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Comment by njvack** [comment]
Yup. And while I think our lab should bump default python versions, doing so would almost certainly cause bustage in apps people run in production.

**Comment by gidden** [comment]
@lmichael107, how would you like to handle Davidson-lab specific commits/PRs vs. general ACI PRs? I assume that we want to continue building on our general ACI content and eventually have PRs for the broader SWC community? @gonuke, do you have an opinion on this?

**Comment by gidden** [comment]
(I know this is in the Davidson-specific branch, I'm just curious if we have a strategy for eventual merges to a more general ACI branch or even the ACI 08 25 branch)

**Comment by lmichael107** [comment]
Hi Matt,

This camp is an exception to our general content and is not intended for later merges. Furthermore, Paul and I are leaning toward completely switching to SWC's new standard curriculum (for 08 25) and taking advantage of the user's local laptop environment instead of using servers (SWC has better installers now). For any of these reasons, I would say that the Davidson curriculum should be treated as it's own thing, but that we should keep parts of the programming curriculum that address general computing concepts (even if they're not common for users of Python, specifically).

**Comment by lmichael107** [comment]
Importantly, this curriculum will be taught in a session that starts at 1pm today, so we need a quick resolution.

**Comment by gidden** [comment]
Of course, thanks for the quick response =).

On Thu, Aug 7, 2014 at 10:49 AM, lmichael107 notifications@github.com
wrote:

> Importantly, this curriculum will be taught in a session that starts at
> 1pm today, so we need a quick resolution.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/UW-Madison-ACI/boot-camps/pull/62#issuecomment-51490932
> .

## 

Matthew Gidden
Ph.D. Candidate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Comment by gonuke** [comment]
Is there something reasonable we can do on the server side to make this transparent to the students?
For example, can we have the right version of iPython in the default PATH, but with a slightly different name e.g. "ipython-swc"?

**Comment by njvack** [comment]
My guess is that "with more time, yes" but this is going down in like two
hours. David?

-n

**Comment by gonuke** [comment]
Or... put a symlink or script to the right path in the repo itself and have students type ./ipython

**Comment by njvack** [comment]
OK, we're gonna get symlinks in /usr/bin for python27 and ipython27, so we don't need anything special here.

**Comment by njvack** [comment]
Just sent this to Nate...

David

On 8/7/14, 11:49 AM, David Thompson wrote:>

> There is a python27 and ipython27 in /usr/bin on poblano.  They start.
> You might want to verify that they do more than start.  :)

On 8/7/14, 11:02 AM, Nate Vack wrote:

> My guess is that "with more time, yes" but this is going down in like
> two hours. David?
> 
> -n
> 
> On Thu, Aug 7, 2014 at 10:57 AM, Paul Wilson <notifications@github.com
> <mailto:notifications@github.com>> wrote:
> 
> ```
> Is there something reasonable we can do on the server side to make
> this transparent to the students?
> For example, can we have the right version of iPython in the default
> PATH, but with a slightly different name e.g. "ipython-swc"?
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/UW-Madison-ACI/boot-camps/pull/62#issuecomment-51491900>.
> ```
> 
> --- <br>You are currently subscribed to bit_help as: dathomps@wisc.edu.
> <br>To unsubscribe click here:
> https://lists.wisc.edu/u?id=11728406.4bdc8b782bd76852789472c6c5bc1514&n=T&l=bit_help&o=35866736
> <br>or send a blank email to
> leave-35866736-11728406.4bdc8b782bd76852789472c6c5bc1514@lists.wisc.edu

## 

David Thompson
Waisman Center Brain Imaging and Behavior Lab
1500 Highland Ave. Room T133
Madison, WI  53705-2280
(608) 265-6608
dthompson (at) waisman (dot) wisc (dot) edu

**Pull request merged**
