### PR TITLE
Remove discussion of `is` in "Write Code for People"

### PR DESCRIPTION
**Pull request by njvack**
It's rarely-used (I write a lot of python and basically never use it) and really special-case-y. It's mostly useful for `if foo is None` but we don't ever cover `None`, so there's that. And `is` doesn't come up in any of the rest of the curriculum.

Anyhow, we never cover whitespace in the current version, (though we claim otherwise!) so we'll need space from somewhere.

### CODE REVIEW

**Comment by lmichael107** [comment]
Hi Nate,

Not that I'm trying to delay, but I'm wondering if this content is still important for learning general programming concepts (not just python). Remember that we're not teaching and intro to python course, but are aiming to get across key concepts, thought process, and best practices that could translate to other languages, as well.

**Comment by njvack** [comment]
You're absolutely correct. In some languages, (c, for example) this distinction is very important. In what I actually do on a day-to-day basis, I think about it approximately never. Maybe this is because I already know this stuff in the back of my head; I'm not sure.

Regardless of whether the concept bears mention, I don't think this actual content is high-enough quality to make this clearer for people.

**Comment by lmichael107** [comment]
What about introducing the concept, as is, but verbally providing the context you just described (c versus python, versus your own practices) to the class. People who don't understand/care may not remember, but we find that students love hearing 'insider' and 'pro' tips that they won't often find in online manuals and tutorials. Based upon what your next response is, I'll merge or not.

**Comment by njvack** [comment]
For now, merge. I may try to bring this back in the part where we're assigning variables to other variables. Bigger fish to fry right now.

**Pull request merged**
