### PR TITLE
Update landing page with draft agenda.

### PR DESCRIPTION
**Pull request by gonuke**
During today's meeting we decided to arrange the schedule around the Best Practices paper (http://arxiv.org/abs/1210.0530).  After creating the list of 10 practices, some seemed more appropriate to a boot camp than others, and the shell doesn't really exist there at all...

Day 1
- Setup help (pre-workshop) [30 min]
- (Motivation) What we know about software engineering : @stevemcgough [45 min]
- The Shell : @gonuke [60 min]
- Automating Workflows == Shell automation and Makefiles : @gonuke [90 min]
- Write Code for People == Variables and Data Structures : @stevemcgough [90 min]
- Write Code for People (II) == Flow Control : @aronnem [75 min]

Day 2
- Don't Repeat Yourself == Functions & Modules : @aronnem [90 min]
- Plan for Mistakes == Testing : @katyhuff [75 min]
- Version Control == VC local : @gidden [90 min]
- Collaborate == VC remote : @gidden [75 min]

These are the proposed teaching assignments.  We hope that all instructors can frame their lessons in the context of the relevant "Best Practices" section.  We hope/expect that this will allow learners to make a better connection between the "how" and the "why".

### CODE REVIEW

**Comment by gonuke** [comment]
I've learned how to preview website changes by running jekyll locally [1]

[1] https://help.github.com/articles/using-jekyll-with-pages

**Comment by gidden** [comment]
I was able to build the pages and they look ok to me.. is this ready for a pull now, @gonuke?

**Comment by gonuke** [comment]
I think we've heard from everyone now, so go ahead and pull @gidden

**Comment by gidden** [comment]
Interesting... they give you the option of deleting the branch now when you merge a pr online. How do people feel about mergers doing this? I personally try to clear my branch history kind of frequently, but I've seen old prs pile up, so I wouldn't mind the merger deleting it for me.

**Pull request merged**
