### PR TITLE
Fixing links

### PR DESCRIPTION
**Pull request by jensv**
I fixed the links so that that "Automating Workflows" links to Ipython Intro links "Write Code for People" links to "Don't Repeat Yourself".
@gidden to which Readme should "Don't Repeat Yourself" link? Is it ../../version-control/git/mobility/Readme.md?

### CODE REVIEW

**Comment by lmichael107** [comment]
Hi Jens,

I believe we'd like to have direct linking to from "Automating Workflows"
to "Write Code for People". In the past, I don't believe we've had
attendees spend time on the "Ipython Into" before; rather, it's there as a
reference.

Paul, am I right, or do we want them to see the "Ipython Intro" before
going on to "Write Code for People I"?

-Lauren

**Comment by jensv** [comment]
Hi Lauren,

I separated the "Ipython Intro" content from "Writing Code for People" based on Paul's suggestion in #28

**Comment by lmichael107** [comment]
Okay. Sorry for my confusion.

-Lauren

**Comment by gonuke** [comment]
To summarize - we did spend time on the "iPython Intro" last time, embedded within the first "Writing Code for People" module.  I suggested to Jens that he put that out as a stand alone piece, my intent being to preserve the flow of the "Writing Code for People" module.

My newest suggestion is that the flow be the following:

"Automating Workflows"  ---> "Writing Code for People" --> a brief aside on iPython --> back to "Writing Code for People"

**Comment by jensv** [comment]
Thanks for the suggestion. I think this will flow better. I made the Ipython Intro an aside in Write Code for People.

"Automating Workflows" ---> "Writing Code for People" --> a brief aside on iPython --> back to "Writing Code for People"--> "Don't Repeat Yourself" ---> ?

**Comment by gonuke** [comment]
I like it - merging.

**Pull request merged**
