### PR TITLE
Collaboration edits

### PR DESCRIPTION
**Pull request by ChristinaLK**
let me know if it's clear!

### CODE REVIEW

**Comment by ChristinaLK** [comment]
change alpha/beta to you/partner for the "base fork" and "head fork" instructions?  Or clearer as alpha/beta?

**Comment by gidden** [comment]
"you/partner" is hard because the context changes based on who "you" are =)

**Comment by ChristinaLK** [comment]
that was indeed my conundrum.  :)

**Comment by gidden** [comment]
fwiw, I went with alpha/beta to eschew gender-based names

**Pull request merged**
