### PR TITLE
shortened python sessions

### PR DESCRIPTION
**Pull request by jensv**
From our last meeting I understood that we wanted to try to fit the python sessions in the afternoon of the first day.
This pull request is my attempt so far. We don't have to merge this. I can make changes on what we discuss at the meeting today.
I combined the sessions variables and data structures into writing code for people for the 1:30-3:00 session. 
I combined the sessions flow control and functions & modules into dont repeat yourself for the 3:15-4:0 session.

Since the Readmes are in new folders and combinations of to files the diff view isn't helpful. 
In the first session I removed the theory of coercion and file i/o (covered in session 2). I also grouped all the string and int / float operations together.
In the second session I shorted some of the codes. I probably didn't cut enough to be able to get through the implant example at the end.

### CODE REVIEW

**Comment by gonuke** [comment]
This looks great.  Thanks @jensv.  I have a few suggestions for discussion:
1. What about moving the intro to iPython into a separate file?  It will cause students to jump around a little, but also demonstrate the concept of "separation of concerns".  While this iPython intro is necessary here, it is not integral to the concept of "Write Code for People".
2. Touch back on the "Write code for people" concept.  I think the reason that this module is the best match for that best practice is that the choice of variable type and variable name can make a huge difference in readability.  I think it is important to draw attention to this as we go and point out that choosing a list over a tuple may ultimately matter in some cases for readability.  It also can't hurt to point out the readability of python thanks to indentation rules.
3. What about nudging the conditions into the first 1/2?  I am not sure it fits well under either best practice, per se, but it might be useful to launch into "Don't repeat yourself" by looking at loops.

**Comment by jensv** [comment]
Thanks. Those are great suggestions. I'll work on them.

**Comment by jensv** [comment]
I added the changes @gonuke suggested and some more emphasis on docstrings in the functions part of "Don't repeat yourself".

**Comment by gonuke** [comment]
This all looks like it's ready to go - great work!

**Pull request merged**
