### PR TITLE
adds a placeholder website

### LINKED ISSUE #1: Build boot-camp page in gh-pages
Using the instructions at https://github.com/swcarpentry/boot-camps/wiki/Boot-Camp-Pages, create a new web page for this boot camp.  It will be fine to have it relatively empty at this point.

### PR DESCRIPTION
**Pull request by gidden**
copied directly from the chicago bootcamp and replaced required values with reasonable values for our boot camp. should fix #1.

### CODE REVIEW

**Comment by katyhuff** [comment]
Shouldn't this have started with a fork rather than a hard copy paste?

**Comment by gidden** [comment]
I forked the UW-Madison-ACI boot-camp repository and followed the
instructions as asked..

**Comment by gidden** [comment]
Or what other kind of fork are you talking about? The instructions in the link in #1 explicitly state: make a directory for your boot camp and use either the index.md or index.html files from the previous directories.

**Comment by katyhuff** [comment]
Right, what I mean is that the step where you actually copied the files from the chicago branch could have been a fork of that gh-pages repo. It would just have made it more clear exactly where you made madison specific changes. You're here, right : https://github.com/swcarpentry/boot-camps/wiki/Stand-Alone-Boot-Camp-Sites ?

**Comment by gidden** [comment]
Yes, and I forked https://github.com/UW-Madison-ACI/boot-camps, of which
gh-pages is a branch.

**Comment by katyhuff** [comment]
I know, and then you copied these two files from a remote branch rather than checking them out. Right?

**Comment by gidden** [comment]
Nope, I copied them from:
https://github.com/UW-Madison-ACI/boot-camps/tree/gh-pages/_posts/2013-01-12-chicago

**Comment by gonuke** [comment]
Hence #2 - I found the various instructions pretty unclear.  What @gidden did seems consistent with https://github.com/swcarpentry/boot-camps/wiki/Boot-Camp-Pages, no?

**Comment by katyhuff** [comment]
Yes, sorry. My mistake.

**Pull request merged**
