### PR TITLE
Remove the discussion of sets

### PR DESCRIPTION
**Pull request by njvack**
From the readme:
“Most introductory python courses do not go over sets this early (or at all), and in the interest of time we're no different.”

Let’s actually not be different; this is a sub-introductory python course, after all. And it's not like we're light on content here.

### CODE REVIEW

**Comment by lmichael107** [comment]
I'll ask the same question here as for "is". If you think this isn't good for people to even be aware of (why it's in the curriculum) for general programming concepts, we can take it out. Otherwise, it's probably not adding that much time, and we actually have more time for this content in the Davidson camp than we've had at past camps. 'Let me know your final decision.

**Comment by njvack** [comment]
I think it goes.

Sets aren't even a construct in all languages; furthermore, we don't say anything about _why_ sets might be important, this just essentially says "oh look, sets exist and you can take the union or intersection of them" and I'm all "OK, so what?"

**Comment by lmichael107** [comment]
Perhaps we should have explained (since you haven't been at previous camps) that it is TOTALLY acceptable/recommended that you provide commentary to the curriculum as you go through. Students love to have more background information and context for the overall relevance of certain programming features versus others, and to hear real-world stories of use. I'll merge or not based upon your next response (but will consider comments from others, if there are any).

**Comment by njvack** [comment]
I just don't want to teach something to my labmates with the comment "I basically never use this and you probably won't either."

**Comment by gonuke** [comment]
This is one of the places we need to improve the connection to the best practices, in this case "Write Code for People".  Sets are an immensely valuable construct because of their unique features in relation to other data structures.

Letting people know that there is a data structure with a different set of interactions and features is very valuable.  We are not teaching Python - we are teaching people to choose their data structures wisely to make their code more readable and maintainable.  Unfortunately, this framing is not complete.

We use sets and their features frequently.

**Comment by njvack** [comment]
I dunno. Maybe we leave this in and y'all can chime in about how sets are cool?

**Comment by lmichael107** [comment]
Resolved without merge needed.

**Pull request closed without merging**
